// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOHCwOxabSq6_b60ha8TqWUGatE67Md40',
    appId: '1:701019520397:web:1ff8d6164a6ae9a43d11c4',
    messagingSenderId: '701019520397',
    projectId: 'siply-359cf',
    authDomain: 'siply-359cf.firebaseapp.com',
    storageBucket: 'siply-359cf.firebasestorage.app',
    measurementId: 'G-55EBGPZ3Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRrWJdsQMByGxSCbpCMTNjCRusEpYG8Fk',
    appId: '1:701019520397:android:c2eeca399ca879f23d11c4',
    messagingSenderId: '701019520397',
    projectId: 'siply-359cf',
    storageBucket: 'siply-359cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArq2yDTRsgswqu3KZRbHhmre_9YUo8AwA',
    appId: '1:701019520397:ios:a7c663472b5a5e313d11c4',
    messagingSenderId: '701019520397',
    projectId: 'siply-359cf',
    storageBucket: 'siply-359cf.firebasestorage.app',
    iosBundleId: 'com.example.siplyQueueSkipOrderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArq2yDTRsgswqu3KZRbHhmre_9YUo8AwA',
    appId: '1:701019520397:ios:a7c663472b5a5e313d11c4',
    messagingSenderId: '701019520397',
    projectId: 'siply-359cf',
    storageBucket: 'siply-359cf.firebasestorage.app',
    iosBundleId: 'com.example.siplyQueueSkipOrderingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOHCwOxabSq6_b60ha8TqWUGatE67Md40',
    appId: '1:701019520397:web:db31ebdc523fbae63d11c4',
    messagingSenderId: '701019520397',
    projectId: 'siply-359cf',
    authDomain: 'siply-359cf.firebaseapp.com',
    storageBucket: 'siply-359cf.firebasestorage.app',
    measurementId: 'G-W1ZDCZMDK7',
  );
}
